export * from "./biodata/biodata.pgSchema";
export * from "./skills/skills.pgSchema";
export * from "./experience/experience.pgSchema";
export * from "./education/education.pgSchema";
export * from "./timestamp.pgSchema"
export * from "./dbStatus/dbStatus.pgSchema"
export * from "./images/image.pgSchema";
export * from "./project/project.pgSchema";
export * from "./relations/index";
export * from "./relations/experience-images.pgSchema";
export * from "./relations/project-images.pgSchema";
